Repository githubtraining/training-manual, pull requests merged in 2020-08, with the labels that each got.

#242 Update issue in GitHub Games repo
  script/create-game-repos
Labels: script

#247 Update super-linter.yml
  .github/workflows/super-linter.yml
Labels: bug

#248 Add human readable name stub
  docs/_sidebar.md
  docs/app_add_human_readable_name.md
  docs/img/name-field.png
  docs/img/userbar-account-settings.png
Labels: enhancement
